### ISSUE TITLE
Different sizes of taken pieces

### ISSUE THREAD

**Issue by alexbagirov** [ChessCorp/chess-sample-ui#2]
Hi, @alcibiade!

We've talked about your new project recently. Currently there is a small UI bug (I suppose it is a bug). When you take some pieces of the same type, they can be shown in different sizes (see the screenshot).

![chess](https://cloud.githubusercontent.com/assets/6885864/9790064/55741d1a-57ed-11e5-873d-91c6591add79.jpg)

**Comment by alexbagirov** [comment]
One more picture to make it clear.

![chess](https://cloud.githubusercontent.com/assets/6885864/9790097/90bb1c2a-57ed-11e5-8d81-d8e8c66c1359.jpg)

**Comment by alcibiade** [comment]
Hi @alexbagirov !

It's not a bug, it's actually a feature, common taken pieces are deliberately made smaller to use less space.

Based on your feedback I understand that you don't like it.

I think that we may either:
* Make the common pieces even smaller to keep focus on differences;
* Make all pieces have the same size and only work on order and spacing to distinguish common and specific pieces...

Do you have a preference ?

**Comment by alexbagirov** [comment]
What do you think about making one icon for each type of piece and adding a small number at the reight\left bottom of it which tells you how much pieces of this type was taken?

**Comment by alcibiade** [comment]
I made some tests but don't like numbers that much.
I rather made an new version which organizes with a single size but different spacing to group pieces by type. I think it may be a good approach and better as my previous one:

![screenshot from 2015-09-12 12 06 54](https://cloud.githubusercontent.com/assets/3389277/9831068/391594d0-5948-11e5-8837-9bfa9758ac0a.png)
